# Generated by Django 4.1.7 on 2023-04-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_date', models.DateTimeField(help_text='投稿日')),
                ('author', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=100)),
            ],
        ),
    ]
